git clone https://github.com/SimpleMobileTools/General-Discussion.git
git clone https://github.com/SimpleMobileTools/Simple-Commons.git
git clone https://github.com/SimpleMobileTools/Simple-Voice-Recorder.git
git clone https://github.com/SimpleMobileTools/Simple-App-Launcher.git
git clone https://github.com/SimpleMobileTools/Simple-Calculator.git
git clone https://github.com/SimpleMobileTools/Simple-Camera.git
git clone https://github.com/SimpleMobileTools/Simple-Clock.git
git clone https://github.com/SimpleMobileTools/Simple-Contacts.git
git clone https://github.com/SimpleMobileTools/Simple-Dialer.git
git clone https://github.com/SimpleMobileTools/Simple-Draw.git
git clone https://github.com/SimpleMobileTools/Simple-File-Manager.git
git clone https://github.com/SimpleMobileTools/Simple-Flashlight.git
git clone https://github.com/SimpleMobileTools/Simple-Keyboard.git
git clone https://github.com/SimpleMobileTools/Simple-Music-Player.git
git clone https://github.com/SimpleMobileTools/Simple-Launcher.git
git clone https://github.com/SimpleMobileTools/Simple-Notes.git
git clone https://github.com/SimpleMobileTools/Simple-SMS-Messenger.git
git clone https://github.com/SimpleMobileTools/Simple-Thank-You.git
git clone https://github.com/SimpleMobileTools/Simple-Calendar.git
git clone https://github.com/SimpleMobileTools/Simple-Gallery.git